### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by cookiemon** [cmus/cmus#262]
cmus segfaults when loading specific mp3 files.
Tested on 2.6 and current git head.
OS: Gentoo Linux 3.17.8 (64-bit)

Backtrace:
```
    #0  ape_parse_one (valp=<optimized out>, keyp=<synthetic pointer>, size=157910, buf=0x7a9980 "\201\201E\201\225ぁE\020") at ape.c:147
    #1  ape_get_comment (ape=ape@entry=0x7fffffffdea0, val=val@entry=0x7fffffffde88) at ape.c:251
    #2  0x00007ffff6c69d0b in mad_read_comments (ip_data=<optimized out>, comments=0x7fffffffe0b8) at mad.c:166
    #3  0x000000000041e849 in ip_read_comments (ip=ip@entry=0x792010, comments=comments@entry=0x7fffffffe108) at input.c:672
    #4  0x000000000040c8a7 in ip_get_ti (filename=filename@entry=0x791fc0 "/home/wardragon/-Band Edition-/02.ワールドイズマイン.mp3") at cache.c:414
    #5  0x000000000040d558 in cache_get_ti (filename=<optimized out>, filename@entry=0x791fc0 "/home/wardragon/-Band Edition-/02.ワールドイズマイン.mp3", force=force@entry=0)
    at cache.c:453
    #6  0x000000000040e3fd in cmus_play_file (filename=0x791fc0 "/home/wardragon/-Band Edition-/02.ワールドイズマイン.mp3") at cmus.c:113
    #7  0x000000000040c1b5 in browser_enter () at browser.c:414
    #8  0x000000000040f025 in cmd_win_activate (arg=0x268d6 <error: Cannot access memory at address 0x268d6>) at command_mode.c:1524
    #9  0x00000000004139ee in run_command (buf=<optimized out>) at command_mode.c:2896
    #10 0x0000000000434189 in u_getch () at ui_curses.c:2088
    #11 main_loop () at ui_curses.c:2208
```

Content of cmus-debug.txt
```
    main: charset = 'UTF-8'
    player_init: using real-time scheduling
    player_init: setting priority to 99
    player_set_op: setting op to ''
    player_error: ERROR: 'selecting output plugin '': no such plugin'
    init_curses: Number of supported colors: 256
    init_curses: ts: 0 fs: 0
    TIMER: worker job:           0.000017
    TIMER: worker job:           0.000007
    error_msg: Error: selecting output plugin '': no such plugin
    id3_tag_size: v2.3.0
    handle_lost_sync: frame 0, skipping ID3 tag (159976 bytes)
    do_open: 
      frames: 9766, br: 320033 b/s, sr: 44100 Hz, ch: 2, layer: 3, joint stereo: 1
      dual channel: 0, vbr: 0, duration: 255.111 s, xing: 1
    mad_read_comments: filename: /home/wardragon/-Band Edition-/02.ワールドイズマイン.mp3
    v2_3_0_frame_header_parse: TIT2 21
    v2_3_0_frame_header_parse: TPE1 9
    v2_3_0_frame_header_parse: TALB 27
    v2_3_0_frame_header_parse: TYER 11
    decode_normal: date before: '2009'
    v2_3_0_frame_header_parse: TRCK 7
    v2_3_0_frame_header_parse: TCON 19
    decode_normal: genre before: 'Vocaloid'
    v2_3_0_frame_header_parse: APIC 157713
```
